name: CI
on: [push]
jobs:
  test_and_build:
    runs-on: ubuntu-latest
    container: gableroux/unity3d:2019.3.7f1-update-2020-03-28

    env:
      UNITY_EDITOR: /opt/Unity/Editor/Unity
      UNITY_DEFAULT_ARGS: -quit -batchmode -nographics -silent-crashes -logFile
      PROJECT_PATH: "./Test Project"

    steps:
        - name: Checkout Project
          uses: actions/checkout@v1
        
        - name: Activate Unity
          env:
            UNITY_ACTIVATION_DATA: ${{ secrets.UNITY_ACTIVATION_DATA }}
            UNITY_ACTIVATION_FILE: ./Activation/Unity_v2019.x.ulf
          # exit 0 since for some reson unity exits with one even if license was successfully activated
          run: mkdir -p $(dirname ${UNITY_ACTIVATION_FILE}) && echo ${UNITY_ACTIVATION_DATA} > ${UNITY_ACTIVATION_FILE} && ${UNITY_EDITOR} ${UNITY_DEFAULT_ARGS} -manualLicenseFile ${UNITY_ACTIVATION_FILE} || exit 0

        - name: Test code
          env:
            TEST_RESULTS_PATH: ./TestResults/results.xml
            TEST_PLATFORM: PlayMode
          run: mkdir -p $(dirname ${TEST_RESULTS_PATH}) && ${UNITY_EDITOR} ${UNITY_DEFAULT_ARGS} -projectPath "${PROJECT_PATH}" -runTests -testPlatform ${TEST_PLATFORM} -testResults ${TEST_RESULTS_PATH}