name: Actions 😎

on: [push]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - TestProject
        unityVersion:
          - 2019.3.7f1
        testMode:
          - playmode
        targetPlatform:
          - StandaloneWindows
          - StandaloneWindows64
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
    
      - name: Cache library
        uses: actions/cache@v1.1.0
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-
            Library-

      - name: Run tests
        id: runTests
        uses: webbertakken/unity-test-runner@v1.3
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          testMode: ${{ matrix.testMode }}
          artifactsPath: test-results-${{ matrix.testMode }}-artifacts

      - name: Actifact test results
        uses: actions/upload-artifact@v1
        with:
          name: Test results for ${{ matrix.testMode }}
          path: ${{ steps.runTests.outputs.artifactsPath }}

      - name: Build game
        id: buildGame
        uses: webbertakken/unity-builder@v0.11
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          buildsPath: build

      - name: Artifact build
        uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build